server:
  port: 8083

spring:
  application:
    name: Feign
  zipkin:
    base-url: http://127.0.0.1:9411/
    sender:
      type: web
    sleuth:
      sampler:
        probability: 1

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
      #eureka client刷新本地缓存时间
      #默认30s
    registry-fetch-interval-seconds: 5
  instance:
    appname: Feign
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

ribbon:
  eureka:
    enabled: true
feign:
  httpclient:
    connection-timeout: 20000
    compression:
      #request:
        #mime-types: text/xml, application/xml, application/json
  #feign调用使用熔断器，如果使用熔断器，但是不设置会报错（默认为false）
  hystrix:
    enabled: true
