server:
  port: 8082

spring:
  application:
    name: Zuul

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
      #eureka client刷新本地缓存时间
      #默认30s
    registry-fetch-interval-seconds: 5
  instance:
    appname: Zuul
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: QRcode
    api-b:
      path: /api-b/**
      serviceId: Email

