server:
  port: 9092

spring:
  application:
    name: Email

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
      #eureka client刷新本地缓存时间
      #默认30s
    registry-fetch-interval-seconds: 5
  instance:
    appname: Email
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}